### ISSUE TITLE
implement true peak without speex dependency

### ISSUE THREAD

**Issue by audionuma** [jiixyj/libebur128#16]
Hello,
ITU R BS 1770 has recently been revised to version 3 whose major modification is to give filter coefficients for the oversampling filter used in the true peak measurement.
http://www.itu.int/rec/R-REC-BS.1770-3-201208-I/en
It would be very nice to have the true-peak measurement implemented directly into libebur128 instead of using the external speex oversampler.
Regards,
Manuel

**Comment by xorgy** [comment]
True peak can exceed the numeric range of your discrete samples, this is because the wave continues between samples.

If you sample a signal, and your peaks have samples on either side of the peak, the true peak is the peak of the sine between those samples(which could be well outside the actual numeric range of the samples, further outside for higher frequencies IIRC).

https://dt7v1i9vyp3mf.cloudfront.net/styles/news_large/s3/imagelibrary/L/Loudness-09.jpg

BS 1770 specifies a standard filter, so that's probably what you want to implement.

**Comment by diogocp** [comment]
In the meanwhile, the Speex dependency should be mentioned in the README.

**Comment by andrewrk** [comment]
@diogocp I made the changes to the README as you suggested in 1fcd50e8ad123c8c5be5cedbf476ae0d26cef429

**Comment by bmatherly** [comment]
I have something working here: https://github.com/jiixyj/libebur128/pull/51

**Comment by jiixyj** [comment]
This was merged for the 1.2.0 release.
